---
mgmt_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + mgmt_if ].ipv4.address }}"
control_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + control_if.device ].ipv4.address }}"
rabbit_hosts: "{% for node in groups['rabbitmq_cluster'] %}{{ hostvars[node]['ansible_'+control_if.device]['ipv4']['address'] }}:{{rabbit_port}}{% if not loop.last %},{% endif %}{% endfor %}"
keystone_adminurl: "{{keystone_admin_protocol}}://{{keystone_admin_vip}}:{{keystone_admin_port}}/{{keystone_default_api_verison}}"
glance_bind_host: "{{ control_ipaddr }}"
glance_vip: "{{haproxy_vip}}"
keystone_vip: "{{haproxy_vip}}"
glance_pass: "{{  lookup('password', credentials_dir + '/credentials/glance_pass chars=ascii_letters,digits') }}"
glance_db_pass: "{{  lookup('password', credentials_dir + '/credentials/glance_db_pass chars=ascii_letters,digits') }}"
lb_db_vip: "{{haproxy_vip}}"
