---
- name: Add VLAN interfaces to VMs
  delegate_to: "{{kvm_host}}"
  command: virsh attach-interface {{ hostname }} network {{ vnics[item]['network'] }} --model virtio --mac {{ vnics[item]['mac_addr'] }} --live --persistent
  with_items: vnics.keys()|sort

- name: Copy ifcfg template
  template:
    src: ifcfg-lvnet.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{vnics[item]['name']}}" 
  with_items: vnics.keys()|sort 

- name: Set eth1 to default route
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    state: present
    regexp: "^DEFROUTE"
    insertafter: EOF
    line: "DEFROUTE=yes"

- name: Restart all interfaces
  service:
    name: network.service
    state: restarted
