---
- name: Add VLAN interfaces to VMs
  delegate_to: "{{kvm_host}}"
  command: virsh attach-interface {{ hostname }} network {{ item.value.network }} --model virtio --mac {{ item.value.mac_addr }} --live --persistent
  with_dict: vnics

- name: Copy ifcfg template
  template:
    src: ifcfg-lvnet.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.value.name }}" 
  with_dict: vnics 

- name: Set eth1 to default route
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    state: present
    regexp: "^DEFROUTE"
    insertafter: EOF
    line: "DEFROUTE=yes"

- name: Restart all interfaces
  service:
    name: network.service
    state: restarted
