---
mgmt_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + mgmt_if ].ipv4.address }}"
control_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + control_if.device ].ipv4.address }}"
heat_bind_host: "{{ control_ipaddr }}"
heat_metadata_server_url: "http://{{ heat_private_vip }}:8000"
heat_waitcondition_server_url: "http://{{ heat_private_vip }}:8000/v1/waitcondition"
heat_watch_server_url: "http://{{ heat_public_vip }}:8003"
keystone_admin_url: "{{keystone_admin_protocol}}://{{keystone_admin_vip}}:{{keystone_admin_port}}"
heat_memcached_servers: "{% for node in groups['heat'] %}{{ hostvars[node]['ansible_'+control_if.device]['ipv4']['address'] }}:{{memcached_port | default(11211)}}{% if not loop.last %},{% endif %}{% endfor %}"
rabbit_hosts: "{% for node in groups['rabbitmq_cluster'] %}{{ hostvars[node]['ansible_'+control_if.device]['ipv4']['address'] }}:{{rabbit_port}}{% if not loop.last %},{% endif %}{% endfor %}"


os_admin_auth2: "--os-auth-url {{ keystone_admin_url }}/v2.0 --os-tenant-name {{admin_tenant}} --os-username {{admin_user }}  --os-password {{admin_pass}}"
os_admin_auth3: "--os-auth-url {{ keystone_admin_url }}/v3 --os-tenant-name {{admin_tenant}} --os-username {{admin_user }}  --os-password {{admin_pass}}"

#vips
heat_private_vip: "{{haproxy_vip}}"
lb_db_vip: "{{haproxy_vip}}"
heat_public_vip: "{{haproxy_vip}}"
keystone_admin_vip: "{{haproxy_vip}}"


#passwords
heat_pass: "{{ lookup('password', credentials_dir + '/credentials/heat_pass chars=ascii_letters,digits') }}"
heat_db_pass: "{{ lookup('password', credentials_dir + '/credentials/heat_db_pass chars=ascii_letters,digits') }}"
heat_admin_pass: "{{ lookup('password', credentials_dir + '/credentials/heat_admin_pass chars=ascii_letters,digits') }}" 
admin_pass: "{{ lookup('password', credentials_dir + '/credentials/admin_pass chars=ascii_letters,digits') }}"
