---
# the interface the api commands will route through. If the api interface is different between compute and control,
# create a new group_vars file for ['ceilomter-controller' and 'compute'] and specify different NICs

#Enable or disable ceilometer
use_ceilometer: true

# Database to be used for ceilometer.  Options: [ 'mariadb', 'mongodb'] if monogo is used, mongodb will be installed.
ceilometer_db: mariadb

#Enable or disable pacemaker
use_pacemaker: false

#for keystone auth construction
keystone_admin_protocol: http
keystone_public_protocol: http
keystone_admin_port: 35357
keystone_public_port: 5000
keystone_default_api_verison: v2.0
admin_tenant: admin
admin_user: admin


