---
# Boolean operator to enable cinder installation
use_cinder: true

# use the nfs volume drivers for cinder
use_cinder_nfs_volume_driver: false

# use cinder drivers for cinder
use_ceph: false

# port that cinder api listens on
cinder_osapi_volume_listen_port: 8776

# location of credentials directory on autodeploy node.
credentials_dir: /var/lib/ansible

#use pacemaker to manage services?
use_pacemaker: false


