---
# subscription manager vars:

# RHN credentials to register systems
# rhn_user: rhn-username
# rhn_pass:  rhn-password

# Specify a subscription pool name to consume. Regular expressions accepted.
pool: Openstack

openstack_release: 'juno'
offline: false

dns_if: eth1

## Global user configurable vars:
#ntp:
#  - 0.rhel.pool.ntp.org
#  - 1.rhel.pool.ntp.org
#  - 2.rhel.pool.ntp.org

#nameservers:
# - 192.168.70.3
#search_domain: ".localdomain"

##rabbit user and password
#rabbit_user: guest
#rabbit_pass: guest

# Statically set Ceilometer Passwords.
# ceilometer_db_pass: "{{ lookup('password', credentials_dir + '/credentials/ceilometer_db_pass chars=ascii_letters,digits') }}"
# ceilometer_pass: "{{ lookup('password', credentials_dir + '/credentials/ceilometer_pass chars=ascii_letters,digits') }}"
# ceilometer_metering_secret: "{{ lookup('password', credentials_dir + '/credentials/ceilometer_metering_secret chars=hexdigits') }}"

## Directory that ansible stores credentials in locally.
# credentials_dir: /var/lib/ansible

## set password for cinder database and
# cinder_db_pass: "{{ lookup('password', credentials_dir + '/credentials/cinder_db_pass chars=ascii_letters,digits') }}"
# cinder_pass: "{{ lookup('password', credentials_dir + /credentials/cinder_pass chars=ascii_letters,digits') }}"


ceilometer_db: mariadb

# VIPs
vip_servername: "{{ haproxy_vip }}"
haproxy_vip: 192.168.101.2

# #Internal VIPs
#  rabbit_vip: "{{haproxy_vip}}"
#  lb_db_vip: "{{haproxy_vip}}"
#  keystone_vip: "{{haproxy_vip}}"
#  glance_vip: "{{haproxy_vip}}"
#  cinder_vip: "{{haproxy_vip}}"
#  nova_vip: "{{haproxy_vip}}"
#  neutron_vip: "{{haproxy_vip}}"
#  horizon_vip: "{{haproxy_vip}}"
#  heat_vip: "{{haproxy_vip}}"
#  ceilometer_vip: "{{haproxy_vip}}"
#  swift_vip: "{{haproxy_vip}}"
#  scaleio_vip: "{{haproxy_vip}}"
# #public VIPs
#  vip_keystone_pub: "{{haproxy_vip}}"
#  vip_glance_pub: "{{haproxy_vip}}"
#  vip_cinder_pub: "{{haproxy_vip}}"
#  vip_nova_pub: "{{haproxy_vip}}"
#  vip_neutron_pub: "{{haproxy_vip}}"
#  vip_horizon_pub: "{{haproxy_vip}}"
#  vip_heat_pub: "{{haproxy_vip}}"
#  vip_ceilometer_pub: "{{haproxy_vip}}"
