# part_power = 2 ^ partition power = partition count. ( The partition is rounded up after calculation.)
part_power: 18
#replica couunt =  The number of times that your data will be replicated in the cluster.
replica_count: 3
# min_part_hours =  Minimum number of hours before a partition can be moved. This parameter increases availability of data by not moving more than one copy of a given data item within that min_part_hours amount of time.
min_part_hours: 24


# interface for swift services (internal) to listen on.  If different between swift storage and swift proxy, create new
# group vars file for each of the mentioned groups.
mgmt_if: eth0
# interface for rsync to use to replicated storage nodes. to listen on.  If different between swift storage and swift proxy, create new
# group vars file for each of the mentioned groups.
rsync_if: eth2
# temp directory for installation purposes.
temporary_dir: /var/lib/ansible
