---
# This playbook will prepare the autodeploynode for use with the DCAF projects.

- name: Configure autodeploynode base requirements
  hosts: localhost
  roles:
    - { role: base, tags: base }

# This play is run separately so that facts can be gathered for the services
# installed during the previous play
- name: Configure autodeploynode services
  hosts: localhost
  roles:
    - { role: dhcp-server, tags: dhcp-server }
    - { role: hanlon-docker, tags: hanlon-docker }
    - { role: hanlon-discover, tags: hanlon-discover }
