---
# This playbook will prepare the autodeploynode for discovery of all nodes.

- name: Configure deployment node for site discovery
  hosts: localhost

  vars:
    hanlon_base_url: http://{{ ansible_default_ipv4.address }}:8026/hanlon/api/v1/
    hnl_mk_image: hnl_mk_debug-image.2.0.1.iso
    hnl_mk_source: https://github.com/csc/Hanlon-Microkernel/releases/download/v2.0.1/
    hnl_mk_local_path: /opt/hanlon/image/
    hnl_mk_path: /home/hanlon/image/{{ hnl_mk_image }}

  roles:
    - dhcp-server

  tasks:

    - name: Check for local copy of Hanlon Microkernel
      stat:
        path: "{{ hnl_mk_local_path }}{{ hnl_mk_image }}"
        get_checksum: false
        get_md5: false
      register: hnl_mk

    - name: Download Hanlon Microkernel
      get_url:
        url: "{{ hnl_mk_source }}{{ hnl_mk_image }}"
        dest: "{{ hnl_mk_local_path }}"
      when: not hnl_mk.stat.exists

    - name: Add a Microkernel Image to Hanlon
      hanlon_image:
        base_url: "{{ hanlon_base_url }}"
        type: mk
        path: "{{ hnl_mk_path }}"

    - name: Add a Discover Only Model to Hanlon
      hanlon_model:
        base_url: "{{ hanlon_base_url }}"
        template: discover_only
        label: discover_only_model
      register: model

    - name: Add a Discover Only Policy to Hanlon
      hanlon_policy:
        base_url: "{{ hanlon_base_url }}"
        policy_template: discover_only
        label: discover_only_policy
        model_uuid: "{{ model.uuid }}"
        is_default: true
