---
# This playbook will prepare the staging directories and retrieve the automation resources for the
# autodeploynode. The resources will be staged locally in the /opt/autodeploy/projects/ and
# opt/autodeploy/resources/ directories.

- name: Stage DCAF automation resources on autodeploynode
  gather_facts: true
  hosts: localhost

  tasks:

    - name: Install required support packages
      yum:
        pkg: "{{ item }}"
        state: present
      with_items: "{{ autodeploy_support_pkgs }}"
      tags: pkgs

    - name: Create the staging directories in /opt/autodeploy
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ projects_base_path }}"
        - "{{ resources_base_path }}"
      tags: paths

    - name: Create the resource directories in the staging directories
      file:
        path: "{{ resources_base_path }}/{{ item }}"
        state: directory
      with_items: "{{ resource_dirs }}"
      tags: paths
