---
# tasks to spin up  VMs based on where they are assigned
- name: Clone base VM for needed clones
  shell: virt-clone --auto-clone -o {{ vm_name }} -n {{ item.hostname }} -m {{ item.mgmt_mac }}
  with_items: 
     - "{{ nodes }}"
  when: "'{{ item.kvm_host }}' == '{{ inventory_hostname }}'"

- name: Add hostnames to inventory
  add_host: 
    name: '{{ item.hostname }}'
    group: '{{ item.type }},nodes'
    ansible_ssh_host: '{{ item.mgmt_ip }}'
  with_items:
     - "{{ nodes }}"

- name: Start all VMs
  virt: 
    command: start
    name: '{{ item.hostname }}'
    uri: qemu:///system
  with_items:
     - "{{ nodes }}"
  when: "'{{ item.kvm_host }}' == '{{ inventory_hostname }}'"

- name: Pausing to let all clones come online
  pause: 
    seconds: 60

- name: Debug VLAN interfaces
  debug:
    msg: "Attaching network {{ item.1 }} to {{ item.0.hostname }}"
  with_subelements:
    - nodes
    - vnics

- name: Add VLAN interfaces to VMs
  shell: "virsh attach-interface {{ item.0.hostname }} network {{ item.1.network }} --model virtio --mac {{ item.1.mac_addr }} --live --persistent"
  with_subelements:
    - nodes
    - vnics
  when: "'{{ item.0.kvm_host }}' == '{{ inventory_hostname }}'"
