---
# tasks to spin up  VMs based on where they are assigned
- name: Clone base VM for needed clones
  shell: virt-clone --auto-clone -o {{ vm_name }} -n {{ hostvars[item].hostname }} -m {{ hostvars[item].mgmt_mac }}
  with_items: 
     - "{{ groups['nodes'] }}"
  when: "'{{ hostvars[item].kvm_host }}' == '{{ inventory_hostname }}'"


- name: Start all VMs
  virt: 
    command: start
    name: '{{ hostvars[item].hostname }}'
    uri: qemu:///system
  with_items:
     - "{{ groups['nodes'] }}"
  when: "'{{ hostvars[item].kvm_host }}' == '{{ inventory_hostname }}'"

