---
- name: Register host to RHSM
  redhat_subscription: 
    state: present
    username: '{{ rhn_user }}'
    password: '{{ rhn_pass }}'
    pool: '{{ pool }}'
  tags:
    - rhsm

- name: Enable OpenStack repos
  command: subscription-manager repos --enable {{ item }}
  with_items: "{{ yum_repos }}"
  tags:
    - rhsm 

- name: Update host packages
  yum:
    state: latest
    name: '*'
  tags:
    - yum
