---
mgmt_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + mgmt_if ].ipv4.address }}"
control_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + control_if.device ].ipv4.address }}"
nova_memcached_servers: "{% for node in groups['controller-nova'] %}{{ hostvars[node]['ansible_'+hostvars[node]['control_if']['device']]['ipv4']['address'] }}:{{memcached_port | default(11211)}}{% if not loop.last %},{% endif %}{% endfor %}"
rabbit_hosts: "{% for node in groups['rabbitmq_cluster'] %}{{ hostvars[node]['ansible_'+hostvars[node]['control_if']['device']]['ipv4']['address'] }}:{{rabbit_port}}{% if not loop.last %},{% endif %}{% endfor %}"
neutron_bind_host: "{{control_ipaddr}}"
neutron_private_vip: "{{haproxy_vip}}"
nova_private_vip: "{{haproxy_vip}}"
keystone_admin_vip: "{{haproxy_vip}}"
keystone_admin_token: "{{ lookup('password', credentials_dir + '/credentials/keystone_admin_token chars=hexdigits') }}"
keystone_public_vip: "{{haproxy_vip}}"
keystone_adminurl: "{{keystone_auth_protocol}}://{{keystone_admin_vip}}:{{keystone_auth_port}}/v2.0"

nova_pass: "{{ lookup('password', credentials_dir + '/credentials/nova_pass chars=ascii_letters,digits') }}"
neutron_pass: "{{ lookup('password', credentials_dir + '/credentials/neutron_pass chars=ascii_letters,digits') }}"
neutron_db_pass: "{{ lookup('password', credentials_dir + '/credentials/neutron_db_pass chars=ascii_letters,digits') }}"
neutron_agent_tunnel_types: "{{neutron_tunnel_type}}"
neutron_ml2_tenant_network_types: "{{neutron_tunnel_type}}"
neutron_ovs_tunnel_type: "{{neutron_tunnel_type}}"
neutron_ovs_tenant_network_type: "{{neutron_tunnel_type}}"

lb_db_vip: "{{haproxy_vip}}"
os_admin_auth2: "--os-auth-url {{ keystone_adminurl }} --os-tenant-name {{admin_tenant}} --os-username {{admin_user }}  --os-password {{admin_pass}}"
admin_pass: "{{ lookup('password', credentials_dir + '/credentials/admin_pass chars=ascii_letters,digits') }}"
