---
- name: unsubscribe
  hosts: openstack
  tasks:

    - name: Unregister from RSHM
      command: subscription-manager unregister
      ignore_errors: yes

    - name: Clean all RHSM attachments
      command: subscription-manager clean
      ignore_errors: yes

- name: reset libvirt and network on kvmhosts
  hosts: kvmhosts
  tasks:
    - name: Stop and undefine all VMs on all hosts
      shell: for i in $(virsh list --all | grep '^ [0-9a-z\-]' | awk '{print $2}'); do virsh destroy $i; virsh undefine $i; done

    - name: Delete all qcow images
      file:
        path: /var/lib/libvirt/images/*.qcow2
        state: absent
      ignore_errors: yes

    - name: Stop and undefine all libvirt networks
      shell: virsh net-destroy lvnet{{ item.value['vlan'] }} ; virsh net-undefine lvnet{{ item.value['vlan'] }}
      with_dict:  "{{ vlan_interface }}"
      ignore_errors: yes

    - name: Delete all OVS bridges
      shell: ovs-vsctl del-br ovsbr{{ item.value['vlan'] }}
      with_dict: '{{vlan_interface}}'
      ignore_errors: yes

    - name: Delete mgmt bridge ifcfg file
      file:
        path: /etc/sysconfig/network-scripts/ifcfg-br0
        state: absent
      ignore_errors: yes

    - name: Reset em3
      command: mv /etc/sysconfig/network-scripts/orig-ifcfg-em3 /etc/sysconfig/network-scripts/ifcfg-em3

    - name: delete ovsbridge ifcfg files
      file:
        path: /etc/sysconfig/network-scripts/ifcfg-ovsbr{{ item.value['vlan'] }}
        state: absent
      ignore_errors: yes
      with_dict: '{{ vlan_interface }}'

    - name: reset bonds
      command: mv /etc/sysconfig/network-scripts/orig-ifcfg-bond0.{{ item.value['vlan'] }} /etc/sysconfig/network-scripts/ifcfg-bond0.{{ item.value['vlan'] }}
      with_dict: '{{ vlan_interface }}'


    - name: Restart interfaces
      service:
        name: network
        state: restarted

    - name: Unregister from RSHM
      command: subscription-manager unregister

    - name: Clean all RHSM attachments
      command: subscription-manager clean

- name: clean up autodeploy for next run
  hosts: autodeploynode
  tasks:
    - name: Remove basevm entry in /etc/hosts
      lineinfile:
        dest: /etc/hosts
        state: absent
        regexp: "^172.*$"

    - name: Gather all VM MAC addresses in MAC table
      shell: arp -na | grep '\s52' | awk -F '[()]' '{print $2}' | cut -f4 -d'.'
      register: arp_macs

    - name: remove vm mac address from arp table
      shell: for i in {{ arp_macs.stdout_lines }} ; do arp -d 172.17.16.$i ; done
      ignore_errors: true

    - name: Remove tempoary files from Ansible host
      file:
        path: /tmp/{{ item }}
        state: absent
      with_items:
        - basevm.qcow2
        - basevm.xml
