---
- name: unsubscribe
  hosts: openstack
  tasks:

    - name: Unregister from RSHM
      command: subscription-manager unregister
      ignore_errors: yes

    - name: Clean all RHSM attachments
      command: subscription-manager clean
      ignore_errors: yes

- name: reset libvirt and network on kvmhosts
  hosts: kvmhosts
  tasks:
    - name: Stop and undefine all VMs on all hosts
      shell: for i in $(virsh list --all | grep '^ [0-9a-z\-]' | awk '{print $2}'); do virsh destroy $i; virsh undefine $i; done

    - name: Delete all qcow images
      file:
        path: /var/lib/libvirt/images/*.qcow2
        state: absent
      ignore_errors: yes

    - name: Stop and undefine all libvirt networks
      shell: virsh net-destroy {{ item.name }} ; virsh net-undefine {{ item.name }}
      with_items: "{{ libvirt_networks }}"
      ignore_errors: yes

    - name: Delete all OVS bridges
      shell: ovs-vsctl del-br {{ item.name }}
      with_items: "{{ ovs_bridges }}"
      ignore_errors: yes

    - name: Delete mgmt bridge ifcfg file
      file:
        path: /etc/sysconfig/network-scripts/ifcfg-br0
        state: absent
      ignore_errors: yes

    - name: Reset em3
      command: mv /etc/sysconfig/network-scripts/orig-ifcfg-em3 /etc/sysconfig/network-scripts/ifcfg-em3

    - name: delete ovsbridge ifcfg files
      file:
        path: /etc/sysconfig/network-scripts/ifcfg-{{item.name}}
        state: absent
      ignore_errors: yes
      with_items: "{{ovs_bridges}}"

    - name: reset bonds
      command: mv /etc/sysconfig/network-scripts/orig-ifcfg-{{item.port}} /etc/sysconfig/network-scripts/ifcfg-{{item.port}}
      with_items: "{{ovs_bridges}}"
     
    - name: Restart interfaces 
      service:
        name: network
        state: restarted 

    - name: Unregister from RSHM
      command: subscription-manager unregister
    
    - name: Clean all RHSM attachments
      command: subscription-manager clean

- name: clean up autodeploy for next run
  hosts: auto_deploy_node
  tasks:
    - name: Remove basevm entry in /etc/hosts
      lineinfile:
        dest: /etc/hosts
        state: absent
        regexp: "^172.*$"
    
    - name: Gather all VM MAC addresses in MAC table
      shell: arp -na | grep '\s52' | awk -F '[()]' '{print $2}' | cut -f4 -d'.'
      register: arp_macs
    
    - name: remove vm mac address from arp table
      shell: for i in {{ arp_macs.stdout_lines }} ; do arp -d 172.17.16.$i ; done
      ignore_errors: true

    - name: Remove tempoary files from Ansible host
      file:
        path: /tmp/{{ item }}
        state: absent
      with_items:
        - basevm.qcow2
        - basevm.xml
