---
# use clustercheck to determine if node is up and syncedi
#
- name: number of node check
  fail:
    msg: " Cluster has {{number_of_nodes}} nodes, This installation requires either a single database host, or an odd number of hosts (3 or more)"
  when: "{{number_of_nodes}} is even or {{number_of_nodes == 2}}"
  run_once: yes
  tags: galera

- name: check to see if mariadb is installed
  shell: rpm -qa mariadb-galera-server 
  register: rpm
  tags: galera

- name: install mariadb-galera
  include: install_galera.yml
  when: '"mariadb-galera-server" not in rpm.stdout'
  tags: galera
  ignore_errors: yes

- name: clustercheck nodes
  command: clustercheck
  register: clustercheck
  tags: galera
  ignore_errors: yes

# only needed when hosts:sql > 1
- name: configure mariadb-galera cluster
  include: config_cluster.yml
  when: 'clustercheck.rc != 0 and {{number_of_nodes}} > 2'
  tags: galera

- name: bootstrap galera_cluster
  include: bootstrap_cluster.yml
  when: 'clustercheck.rc != 0 and {{number_of_nodes}} > 2'
  tags: galera

- name: created_DBs
  include: create_db.yml
  when: ('"command not found" in clustercheck.stdout') or (clustercheck.rc != 0)
  tags: galera
