---
# This role is used for updating the base vm before cloning

- name: Disable NetworkManager
  service:
    name: NetworkManager
    enabled: no
    state: stopped

- name: Enable network.service
  service:
    name: network
    enabled: yes
    state: started

- name: Unregister from RHSM
  redhat_subscription: 
    state: absent

- name: Clean all RHSM attachments
  command: subscription-manager clean

- name: Initiating clean shut down of VM
  command: shutdown -h +1
  ignore_errors: True
