---
# This role is used for updating the base vm before cloning

- name: Checking variable presence
  debug:
    msg: "RHSM user is {{ rhsm_user }}"

- name: Register to RHSM
  redhat_subscription: 
    state: present
    username: '{{ rhsm_user }}'
    password: '{{ rhsm_pass }}'
    pool: '{{ rhsm_pool }}'
  tags:
    - rhsm

- name: Running yum update
  yum: 
    name: '*'
    state: latest
  tags:
    - yum

- name: Disable NetworkManager
  service:
    name: NetworkManager
    enabled: no
    state: stopped

- name: Enable network.service
  service:
    name: network
    enabled: yes
    state: started

- name: Unregister from RHSM
  redhat_subscription: 
    state: absent

- name: Clean all RHSM attachments
  command: subscription-manager clean

- name: Initiating clean shut down of VM
  command: shutdown -h +1
  ignore_errors: True
