---
# The smbios-uuid is an identifier used for bare metal deployments.
smbios_uuid: { retrieve for each host using hardware vendor management tools }

# IPMI and PXE IP address
ipmi_ip_address: x.x.x.x
pxe_ip_address: x.x.x.x

# Host name and IP addresses
hostname: cscesxtmp002
mgmt_ip_address: x.x.x.x
vmotion_ip_address: x.x.x.x
vsan_ip_address: x.x.x.x

