---
mgmt_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + mgmt_if ].ipv4.address }}"
control_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + control_if.device ].ipv4.address }}"
mongodb_bind_host: "{{ control_ipaddr }}"
