---
- name: Install virtualization packages
  yum:
    state: latest
    name: '{{ item }}'
  with_items: '{{ virt_rpms }}'

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Enable and start OVS service
  service:
    name: openvswitch
    state: started
    enabled: yes

- name: Enable and start libvirt service
  service:
    name: libvirtd
    state: started
    enabled: yes
