---
mgmt_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + mgmt_if ].ipv4.address }}"
control_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + control_if.device ].ipv4.address }}"
ceilometer_bind_host: "{{ control_ipaddr }}"
ceilometer_memcached_servers: "{% for node in groups['ceilometer-control'] %}{{ hostvars[node]['ansible_'+control_if.device]['ipv4']['address'] }}:{{memcached_port | default(11211)}}{% if not loop.last %},{% endif %}{% endfor %}"
rabbit_hosts: "{% for node in groups['rabbitmq_cluster'] %}{{ hostvars[node]['ansible_'+control_if.device]['ipv4']['address'] }}:{{rabbit_port}}{% if not loop.last %},{% endif %}{% endfor %}"
mongodb_servers: "{% for node in groups['mongodb'] %}{{ hostvars[node]['ansible_hostname'] }}:{{ mongodb_port | default(27017) }}{% if not loop.last %},{% endif %}{% endfor %}"
ceilometer_db_pass: "{{ lookup('password', credentials_dir + '/credentials/ceilometer_db_pass chars=ascii_letters,digits') }}"
ceilometer_pass: "{{ lookup('password', credentials_dir + '/credentials/ceilometer_pass chars=ascii_letters,digits') }}"
ceilometer_metering_secret: "{{ lookup('password', credentials_dir + '/credentials/ceilometer_metering_secret chars=hexdigits') }}"

lb_db_vip: "{{haproxy_vip}}"
keystone_admin_vip: "{{haproxy_vip}}"
