---
# The ip and pxe ip address of the host
ansible_ssh_host: 192.168.0.249
pxe_ip_address: 192.17.16.249

# The smbios-uuid is an identifier used for bare metal deployments.
smbios_uuid: 564DF657-3737-EF45-3AF1-E26FB3CE307F

# Disk partitioning variables controlled by the partition_additional_disks variable in /inventory/group_vars/all.yml.
disk: sdb
fstype: xfs
mount: /data
mount_opts: defaults

# The network bond(s) controlled by the configure_network_bond variable in /inventory/group_vars/all.yml. The bond configuration
# variables are found in the /roles/bonds/defaults/main.yml.
network_bond:
  - bond0
  - bond1

# The bond interfaces to be used for each bond. Note that the actual bonds (bond0 & bond1) do not need a 'master' value
# as they are the bond master. Change these variables per network requirements.
bond_device:
  - { interface: bond0 }
  - { interface: bond1 }
  - { interface: eno33554992, master: bond0 }
  - { interface: eno50332216, master: bond1 }

# The vlan interfaces to be added to the network bond. The default variables common to all of these interfaces are found in the
# /roles/iface/defaults/main.yml. The variables located here are specific to the vlan interface. Change these variables as needed
# per network requirements.
vlan_interface:
  vlan_if1:
    bond: "bond0"
    vlan: "1801"
    ipaddr: "192.17.17.138"
    netmask: "255.255.255.0"
    gateway: "192.17.17.2"
    defroute: "yes"

  vlan_if2:
    bond: "bond0"
    vlan: 1802
    ipaddr: "192.17.17.139"
    netmask: "255.255.255.0"

  vlan_if3:
    bond: "bond1"
    vlan: 1803
    ipaddr: "192.17.17.140"
    netmask: "255.255.255.0"

  vlan_if4:
    bond: "bond1"
    vlan: 1804
    ipaddr: "192.17.17.141"
    netmask: "255.255.255.0"
