---
- name: Add host reservations to dhcpd.conf
  lineinfile:
    dest: /etc/dhcp/dhcpd.conf
    state: present
    regexp: '{{item.mgmt_mac}}'
    #insertafter: EOF
    line: 'host {{ item.hostname }} { hardware ethernet {{ item.mgmt_mac }}; fixed-address {{ item.mgmt_ip }}; }'
  with_items:
    - "{{ dhcpd_hosts }}"

- name: Restart dhcpd 
  service:
    name: dhcpd
    state: restarted
