---
- name: gather facts about neutron-server
  hosts: controller 
  gather_facts: true

- name: setup neutron network-node
  hosts: neutron-network-node
  max_fail_percentage: 0
  roles:
    - subscription-manager
    - role: common
      group: neutron-server 
    - role: common
      group: neutron-network-node
    - role: iface
      device: "{{ ext_if.device }}"
      params:
        devicetype: ovs
        type: OVSPort
        vlan: '"yes"'
        nm_controlled: '"no"'
        nozeroconf: '"yes"'
        ovs_bridge: br-ex
        onboot: '"yes"'
        peerdns: '"no"'
    - role: iface
      device: br-ex
      params:
        devicetype: ovs
        type: OVSBridge
        onboot: '"yes"'
        ovsbootproto: static
        nozeroconf: '"yes"'
        ipaddr: "{{ ext_if.ipaddr }}"
        netmask: "{{ ext_if.netmask }}"
        peerdns: '"no"'
  tasks:
  - name: iptable rules for neutron-network-node
    iptables:
      port: "{{ item.port }}"
      protocol: "{{ item.protocol}}"
      comment: "{{item.comment}}"
      position: 4
    with_items:
    - { port: 67, protocol: udp, comment: "dhcp incoming" }
    - { port: 68, protocol: udp, comment: "dhcp incoming" }
    - { port: 4789, protocol: tcp, comment: "neutron tunnels"}
    - { port: 4789, protocol: udp, comment: "neutron tunnels"}

- name: install neutron
  hosts: neutron-network-node
  max_fail_percentage: 0  
  roles:
    - neutron-common
    - neutron-ovs-agent
    - neutron-network-node

