---
# Usage:
#  bare-metal-os/site_deploy
# edit the inventory.csv file and specify the disk vars
partition_additional_disks: false

# Usage:
#  bare-metal-os/site_deploy (conditional vars to invoke bare-metal-os/roles/bonds & bare-metal-os/roles/iface)
configure_network_bond: true
configure_vlan_interfaces: true

# Usage:
#   bare-metal-os/inventory/host_vars/autodeploynode
#   bare-metal-os/site_deploy (vars/hanlon.yml)
#   bare-metal-os/site_reset (vars/hanlon.yml)
autodeploynode: x.x.x.x

# Usage:
#   bare-metal-os/site_deploy (ifcfg template)
dns1: x.x.x.x

# Usage:
#   bare-metal-os/site_inventory
inventory_path: ./inventory/
inventory_csv_file: ./inventory/example_inventory.csv

# Usage:
#   bare-metal-os/site_deploy
site_password: localpassword

# Usage:
#   bare-metal-os/roles/prepare
rhn_user: 'rhn-user-name'
rhn_pass: 'rhn-password'

# Usage:
#   bare-metal-os/roles/idrac
#   bare-metal-os/site_deploy
#   bare-metal-os/site_inventory
#   bare-metal-os/site_reset
ipmi_username: root
ipmi_password: localpassword
