---
mgmt_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + mgmt_if ].ipv4.address }}"
control_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + control_if.device ].ipv4.address }}"
keystone_public_bind_host: "{{ control_ipaddr }}"
keystone_admin_bind_host: "{{ mgmt_ipaddr }}"
keystone_memcached_servers: "{% for node in groups['keystone'] %}{{ hostvars[node]['ansible_'+control_if.device]['ipv4']['address'] }}:{{memcached_port | default(11211)}}{% if not loop.last %},{% endif %}{% endfor %}"
rabbit_hosts: "{% for node in groups['rabbitmq_cluster'] %}{{ hostvars[node]['ansible_'+control_if.device]['ipv4']['address'] }}:{{rabbit_port}}{% if not loop.last %},{% endif %}{% endfor %}"
keystone_adminurl: "{{keystone_admin_protocol}}://{{keystone_admin_vip}}:{{keystone_admin_port}}/{{keystone_default_api_verison}}"
swift_public_vip: "{{ swift_vip}}"
swift_admin_vip: "{{ swift_vip }}"
swift_private_vip: "{{ swift_vip }}"

keystone_public_vip: "{% if keystone_vip != vip_keystone_pub %}{{ vip_keystone_pub }}{% else %}{{keystone_vip}}{% endif %}"
keystone_admin_vip: "{{ keystone_vip }}"
keystone_private_vip: "{{ keystone_vip }}"

glance_public_vip: "{% if glance_vip != vip_glance_pub %}{{ vip_glance_pub }}{% else %}{{glance_vip}}{% endif %}"
glance_admin_vip: "{{ glance_vip }}"
glance_private_vip: "{{ glance_vip }}"

cinder_public_vip: "{% if cinder_vip != vip_cinder_pub %}{{ vip_cinder_pub }}{% else %}{{cinder_vip}}{% endif %}"
cinder_admin_vip: "{{ cinder_vip }}"
cinder_private_vip: "{{ cinder_vip }}"

nova_public_vip: "{% if nova_vip != vip_nova_pub %}{{ vip_nova_pub }}{% else %}{{nova_vip}}{% endif %}"
nova_admin_vip: "{{ nova_vip }}"
nova_private_vip: "{{ nova_vip }}"

neutron_public_vip: "{% if neutron_vip != vip_neutron_pub %}{{ vip_neutron_pub }}{% else %}{{neutron_vip}}{% endif %}"
neutron_admin_vip: "{{ neutron_vip }}"
neutron_private_vip: "{{ neutron_vip }}"

horizon_public_vip: "{% if horizon_vip != vip_horizon_pub %}{{ vip_horizon_pub }}{% else %}{{horizon_vip}}{% endif %}"
horizon_private_vip: "{{ horizon_vip }}"

heat_public_vip: "{% if heat_vip != vip_heat_pub %}{{ vip_heat_pub }}{% else %}{{heat_vip}}{% endif %}"
heat_admin_vip: "{{ heat_vip }}"
heat_private_vip: "{{ heat_vip }}"

ceilometer_public_vip: "{% if ceilometer_vip != vip_ceilometer_pub %}{{ vip_ceilometer_pub }}{% else %}{{ceilometer_vip}}{% endif %}"
ceilometer_admin_vip: "{{ ceilometer_vip }}"
ceilometer_private_vip: "{{ ceilometer_vip }}"

##VIPS
#Internal VIPs
rabbit_vip: "{{haproxy_vip}}"
lb_db_vip: "{{haproxy_vip}}"
keystone_vip: "{{haproxy_vip}}"
glance_vip: "{{haproxy_vip}}"
cinder_vip: "{{haproxy_vip}}"
nova_vip: "{{haproxy_vip}}"
neutron_vip: "{{haproxy_vip}}"
horizon_vip: "{{haproxy_vip}}"
heat_vip: "{{haproxy_vip}}"
ceilometer_vip: "{{haproxy_vip}}"
swift_vip: "{{haproxy_vip}}"
scaleio_vip: "{{haproxy_vip}}"
#public VIPs
vip_keystone_pub: "{{haproxy_vip}}"
vip_glance_pub: "{{haproxy_vip}}"
vip_cinder_pub: "{{haproxy_vip}}"
vip_nova_pub: "{{haproxy_vip}}"
vip_neutron_pub: "{{haproxy_vip}}"
vip_horizon_pub: "{{haproxy_vip}}"
vip_heat_pub: "{{haproxy_vip}}"
vip_ceilometer_pub: "{{haproxy_vip}}"

#Keystone admin passwords
credentials_dir: /var/lib/ansible
#openstack service user passwords
admin_pass: "{{ lookup('password', credentials_dir + '/credentials/admin_pass chars=ascii_letters,digits') }}"
glance_pass: "{{ lookup('password', credentials_dir + '/credentials/glance_pass chars=ascii_letters,digits') }}"
cinder_pass: "{{ lookup('password', credentials_dir + '/credentials/cinder_pass chars=ascii_letters,digits') }}"
swift_pass: "{{ lookup('password', credentials_dir + '/credentials/swift_pass chars=ascii_letters,digits') }}"
neutron_pass: "{{ lookup('password', credentials_dir + '/credentials/neutron_pass chars=ascii_letters,digits') }}"
nova_pass: "{{ lookup('password', credentials_dir + '/credentials/nova_pass chars=ascii_letters,digits') }}"
heat_pass: "{{ lookup('password', credentials_dir + '/credentials/heat_pass chars=ascii_letters,digits') }}"
ceilometer_pass: "{{ lookup('password', credentials_dir + '/credentials/ceilometer_pass chars=ascii_letters,digits') }}"
keystone_admin_token: "{{ lookup('password', credentials_dir + '/credentials/keystone_admin_token chars=hexdigits') }}"
swift_pathprefix: "{{ lookup('password', credentials_dir + '/credentials/swift_prefix chars=ascii_letters,digits') }}"
swift_pathsuffix: "{{ lookup('password', credentials_dir + '/credentials/swift_suffix chars=ascii_letters,digits') }}"
demo_pass: "{{ lookup('password', credentials_dir + '/credentials/admin_pass chars=ascii_letters,digits') }}"
neutron_metadata_proxy_shared_secret: "{{ lookup('password', credentials_dir + '/credentials/neutron_metadata_proxy_shared_secret chars=hexdigits') }}"

#database user passwords
keystone_db_pass: "{{ lookup('password', credentials_dir + '/credentials/keystone_db_pass chars=ascii_letters,digits') }}"
