---
#rabbit_hosts: "{% for node in groups['rabbitmq_cluster'] %}{{ hostvars[node]['ansible_'+control_if.device]['ipv4']['address'] }}:{{rabbit_port|default(5672)}}{% if not loop.last %},{% endif %}{% endfor %}"
rabbit_hosts: "{% for node in groups['rabbitmq_cluster'] %}{{ hostvars[node]['control_if']['ipaddr'] }}:{{rabbit_port|default(5672)}}{% if not loop.last %},{% endif %}{% endfor %}"
control_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + control_if.device ].ipv4.address }}"
mgmt_ipaddr: "{{ hostvars[inventory_hostname][ 'ansible_' + mgmt_if ].ipv4.address }}"

nova_public_vip: "{{haproxy_vip}}"
nova_private_vip: "{{haproxy_vip}}"
lb_db_vip: "{{haproxy_vip}}"
glance_vip: "{{haproxy_vip}}"
neutron_vip: "{{haproxy_vip}}"
keystone_vip: "{{ haproxy_vip }}"

nova_pass: "{{ lookup('password', credentials_dir + '/credentials/nova_pass chars=ascii_letters,digits') }}"
nova_db_pass: "{{ lookup('password', credentials_dir + '/credentials/nova_db_pass chars=ascii_letters,digits') }}"
neutron_pass: "{{ lookup('password', credentials_dir + '/credentials/neutron_pass chars=ascii_letters,digits') }}"
neutron_metadata_proxy_shared_secret: "{{ lookup('password', credentials_dir + '/credentials/neutron_metadata_proxy_shared_secret chars=hexdigits') }}"


