keystone_adminurl: "{{ keystone_auth_protocol|default('http') }}://{{ keystone_vip }}:{{ keystone_auth_port | default('35357') }}/v2.0"
os_admin_auth: "--os-auth-url {{ keystone_adminurl}} --os-tenant-name {{admin_tenant}} --os-username {{admin_user }}  --os-password {{admin_pass}}"
os_demo_auth: "--os-auth-url {{ keystone_adminurl}} --os-tenant-name {{demo_tenant}} --os-username {{demo_user }}  --os-password {{admin_pass}}"
ext_gateway: "{{demo_ext_network | ipaddr('net') | ipaddr('1') | ipaddr('address')}}"
start_ext_allocation: "{{demo_ext_network | ipaddr('net') | ipaddr('100') | ipaddr('address')}}"
end_ext_allocation: "{{demo_ext_network | ipaddr('net') | ipaddr('200') | ipaddr('address')}}"


credentials_dir: /var/lib/ansible
#openstack service user passwords
admin_pass: "{{ lookup('password', credentials_dir + '/credentials/admin_pass chars=ascii_letters,digits') }}"
demo_pass: "{{ lookup('password', credentials_dir + '/credentials/admin_pass chars=ascii_letters,digits') }}"

keystone_vip: "{{haproxy_vip}}"
