---
- name: Create Ansible Inventory
  hosts: localhost
  gather_facts: False

  tasks:

  - name: Create Ansible inventory from CSV file
    create_inventory:
      file:  "{{ inventory_csv_file }}"
      path: "{{ inventory_path }}"


- name: Update Ansible Inventory with SMBIOS UUID
  hosts: deploy
  max_fail_percentage: 0
  gather_facts: False

  tasks:

  - name: Retrieve SMBIOS UUID through IPMI
    local_action:
      module: ipmi_facts
      hostname: '{{ ipmi_ip_address }}'
      username: '{{ ipmi_username }}'
      password: '{{ ipmi_password }}'
    when: ipmi_ip_address is defined
    register: ipmi

  - name: Update Inventory host_vars with SMBIOS UUID
    local_action:
      module: lineinfile
      dest: "{{ inventory_path }}/host_vars/{{ inventory_hostname }}.yml"
      regexp: '^smbios_uuid:'
      line: "smbios_uuid: {{ ipmi.smbios_uuid|upper }}"
      state: present
    when: ipmi.smbios_uuid is defined
