---

# Offline autodeploy vars
offline: false
use_bare_metal_os: true

# Autodeploy common vars
autodeploy_base_path: /opt/autodeploy
docker_api_version: "1.20"
docker_path: "{{ resources_base_path }}/docker/"
projects_base_path: "{{ autodeploy_base_path }}/projects"
resources_base_path: "{{ autodeploy_base_path }}/resources"

# Autodeploy site_discovery vars:
hnl_mk_image: hnl_mk_debug-image.2.0.1.iso
hnl_mk_source: https://github.com/csc/Hanlon-Microkernel/releases/download/v2.0.1/
hnl_mk_local_path: /opt/hanlon/image/
hnl_mk_path: /home/hanlon/image/{{ hnl_mk_image }}

git_repos:
  - { name: "slimer", repo: "https://github.com/csc/slimer.git" }
  - { name: "ansible-scaleio", repo: "https://github.com/csc/ansible-scaleio.git" }

autodeploy_support_pkgs:
  - dhcp
  - docker
  - firefox
  - genisoimage
  - httpd
  - ipmitool
  - iptables-services
  - ntp
  - python-netaddr
  - python-passlib
  - python-pip
  - python-xvfbwrapper
  - sshpass
  - unzip
  - vim
  - wget
  - xorg-x11-server-Xvfb
  - yum-utils
  - openssl-devel
  - glibc.i686

source_projects:
  - ansible-scaleio
  - slimer

resource_dirs:
  - ISO
  - scaleio
