---
- name: install horizon packages
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
    - mod_wsgi
    - httpd
    - mod_ssl
    - python-memcached
    - openstack-dashboard
  tags: horizon

- name: configure dashboard vhost
  template:
    src: kilo_local_settings.j2
    dest: /etc/openstack-dashboard/local_settings
    mode: 0644
    owner: root
    group: root
  tags: horizon

- name: reload daemon
  command: systemctl daemon-reload
  tags: horizon

- name: restart horizon
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - openstack-nova-novncproxy
    - httpd
    - memcached
  tags: horizon



#- name: "[pacemaker]restart nova-consoleauth"
#  command: pcs resource restart nova-consoleauth
#  run_once: true
#  tags: horizon
#  when: use_pacemaker

