---

- name: Gather all registered virtual machines
  vmware_vm_facts: >
    hostname={{ groups['foundation_esxi'][0] }}
    username={{ esxi_username }}
    password={{ site_passwd }}
  register: vmware_facts
  delegate_to: localhost

- name: Use OVFTool to deploy vCenter Appliance
  command: >
    /usr/bin/ovftool
    --acceptAllEulas
    --skipManifestCheck
    --noSSLVerify
    --disableVerification
    --X:injectOvfEnv --powerOn "--net:Network 1=PXE-Network"
    --datastore="vsanDatastore"
    --diskMode=thin
    --name={{ hostname }}
    --prop:vami.hostname={{ hostname }}
    --prop:vami.DNS.VMware_vCenter_Server_Appliance={{ dns_server }}
    --prop:vami.gateway.VMware_vCenter_Server_Appliance={{ mgmt_gateway }}
    --prop:vami.ip0.VMware_vCenter_Server_Appliance={{ mgmt_ip_address }}
    --prop:vami.netmask0.VMware_vCenter_Server_Appliance={{ mgmt_subnet_mask }}
      {{ vcsa_ova }}
      'vi://{{ esxi_username }}:{{ site_passwd }}@{{ groups['foundation_esxi'][0] }}/'
  register: ovftool_result
  when: vmware_facts["virtual_machines"][hostname] is not defined
  delegate_to: localhost

- name: Wait for the vCenter appliance to boot
  local_action: >
    wait_for port=22 host={{ mgmt_ip_address }}
    search_regex=OpenSSH
    delay=10
    timeout=300
  when: ovftool_result.changed
