{% for network in heat_network %}
  {{network}}
    type: OS::Neutron::Net
    properties:
      name: {{heat_network[network]['name']}}

  {{network}}_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network }
      cidr: {{heat_network[network]['ip']}}/{{heat_network[network]['prefix']}}
      enable_dhcp: {{heat_network[network]['enable_dhcp']}}


{% endfor %}
{{heat_network['control']}}
